### ISSUE TITLE
Sonarqube használata

### ISSUE THREAD

**Issue by nkelemen18** [BME-MIT-IET/Emiliano-Jr-Andrew-Cole-Industries-iet-2019#1]
- [x] Sonarqube beüzemelése

- [x] Sonarqube bekötése a projektbe

- [x] Statikus analízis eszköz futtatása

@balint355 
@eeervin 
@Heroleo89 
@nkelemen18

**Comment by Heroleo89** [comment]
A gradle.properties és build.gradle file-okba felvettük a megfelelő adatokat. A sonarqube elindítása után, lebuildeltük a project-et, majd a "gradlew sonarqube" parancsot kiadva elemezte a projectet a sonarqube, ami látható is volt a localhost:9000 porton.

**Comment by nkelemen18** [comment]
Első statikus elemzés áttekintése

![sonarqube_1](https://user-images.githubusercontent.com/16690839/56976373-15a42200-6b73-11e9-92dd-4278fdff591f.png)
