### ISSUE TITLE
JUnit tests

### ISSUE THREAD

**Issue by eeervin** [BME-MIT-IET/Emiliano-Jr-Andrew-Cole-Industries-iet-2019#20]
- [x] AccountDbAdapter class

- [x] OfxHelper class

- [x] OfxAccountType Conversion test

- [x] Account class

**Comment by Heroleo89** [comment]
OfxHelper Test: Checking if the helper class outputs the desired timeformat. // 20190101000000[+...]

**Comment by eeervin** [comment]
AccountDbAdapter Test: Make MartAsExported test.

**Comment by Heroleo89** [comment]
In exsisting test class: AccountTest, added test : accountTypeConverterTest.

**Comment by eeervin** [comment]
AccountDbAdapterTest: Make UpdateAllAccounts test.

**Comment by nkelemen18** [comment]
I've fixed the canMarkAsExported test. There was two problems:

1. Transaction should have a Split (the amount of money) else it won't be saved
2. The Account.getTransactions() won't work if the account is from a list (getSimpleAccountList()). We should use getRecord() for fetch account and select his transactions.

Besides that I added some asserts to test the account's transactions are fetched correctly.

**Comment by eeervin** [comment]
AccountDbAdapterTest: Make UpdateAccount test.

**Comment by eeervin** [comment]
AccountDbAdapterTest: Extend shouldReassignDescendantAccounts method with test with root account type.

**Comment by eeervin** [comment]
AccountTest: Create getBalance test.

**Comment by Heroleo89** [comment]
[coverageBeforeUnitTests.zip](https://github.com/BME-MIT-IET/Emiliano-Jr-Andrew-Cole-Industries-iet-2019/files/3195415/coverageBeforeUnitTests.zip)

result of CoverageTest  before additional unit tests
