### ISSUE TITLE
Bugfix #4 Throw statement in finnaly block

### ISSUE THREAD

**Issue by Heroleo89** [BME-MIT-IET/Emiliano-Jr-Andrew-Cole-Industries-iet-2019#8]
Bug example : 

public static void doSomethingWhichThrowsException() {
  try {
    throw new RuntimeException();
  } finally {
    for (int i = 0; i < 10; i ++) {
      //...
      if (q == i) {
        break; // ignored
      }
    }

    /* ... */
    _return;_      **// Noncompliant - prevents the RuntimeException from being propagated**
  }
}

**Comment by balint355** [comment]
Fixed by #12
